services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    DawBed\UserRegistrationBundle\:
        resource: '../../../UserRegistrationBundle/*'
        exclude: '../../../UserRegistrationBundle/{DependencyInjection,Entity,Migrations,Tests}'
    DawBed\UserRegistrationBundle\Controller\:
        resource: '../../../UserRegistrationBundle/Controller'
        tags: ['controller.service_arguments']

