DawBed\UserBundle\Entity\User\User:
      constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            groups: [registration]
      properties:
         email:
           - NotBlank: { groups: [registration] }
           - Email: { groups: [registration] }
DawBed\UserBundle\Domain\User\CreateModel:
      constrainsts:
         - Symfony\Component\Validator\Constraints\Vadlid:
             fielsds: [entity]
      properties:
         entity:
           - NotBlank: ~
           - Valid: ~
         password:
           - NotBlank: ~

